### ISSUE TITLE
Syntax for picture parameter 

### ISSUE THREAD

**Issue by jeff962** [April-Gras/obsidian-auto-timelines#16]
I haven't been able to guess the format for the aat-event-picture: parameter.  Could you add this to the documentation?

**Comment by April-Gras** [comment]
Added missing documentation in https://github.com/April-Gras/obsidian-auto-timelines/commit/f961ae52db63093b21c921057208e0bac470d452

#### Aditional metadata keys

Sometimes the content of a note is not exacly what you want to appear in the card.
To remedy that, the plugin exposes three keys that are by default:
```yml
aat-event-title: New title # Used to override the title of a generated card.
aat-event-body: New card body # Used to override the text content of a generated card.
aat-event-picture: https://f4.bcbits.com/img/a1344871335_65 #Some external link, support for internal links is missing for now
```

thanks for the suggestion, hope it helps
