### ISSUE TITLE
Timelines ignore tags

### ISSUE THREAD

**Issue by mellypop** [April-Gras/obsidian-auto-timelines#3]
I am trying to render two distinct timelines, but the events I create are showing up on both timelines, regardless of which timelines are tagged, and I'm not sure what I'm doing wrong. For now, I have three events:

```yaml
aat-event-start-date: 1
aat-event-end-date: 316
aat-render-enabled: true
timelines: ['complete']
```

```yaml
aat-event-start-date: 317
aat-event-end-date: true
aat-render-enabled: true
timelines: ['complete']
```

```yaml
aat-event-start-date: 317
aat-event-end-date: 317
aat-render-enabled: true
timelines: ['brightwind']
```

And I have two timelines that look like these (without the leading backslashes):

```
\```aat-vertical
complete
\```
```
```
\```aat-vertical
brightwind
\```
```
